### ISSUE TITLE
版本从1.7.1 升级到8.2.0之后dws sql无法判断传入参数的属性的类型

### ISSUE THREAD

**Issue by Wik-i** [huaweicloudDocs/dws#1]
版本从1.7.1 升级到8.2.0之后。dws sql无法判断传入参数的属性的类型。pojo是传入的对象的msgKey参数是String类型。但是下面的代码会报无法判断 msgKey参数类型的错误。之前的代码：
select * from some_table where attribute like CONCAT('%',#{pojo.msgKey},'%')
修改为
select * from some_table where attribute like CONCAT('%',#{pojo.msgKey}::text,'%')
可以解决问题。
但是为什么无法判断对象的属性类型，甚至连 List<String> 的参数也无法判断类型。是否可以增加支持，保证1.7.1的兼容性。业务有同一个sql两个使用场景的情况（mysql和postgresql），所以可以使8.x版本拥有和1.7.1版本一样的特性

**Comment by Wik-i** [comment]
![image](https://user-images.githubusercontent.com/52619695/222678463-0972599c-9940-4502-8ff4-31f3cfb26227.png)

**Comment by luhuayi** [comment]
如沟通，产品功能，建议提需求跟踪。

**Comment by luhuayi** [comment]
内部用户，通过需求实现，沟通闭环。
